language: node_js
node_js:
    - "6"

branches:
    only:
        - master

cache:
    directories:
        - node_modules

script:
    - npm run build.prod

deploy:
    provider: heroku
    api_key: $HEROKU_TOKEN
    app: angulartictactoe
    run: "node server.js"